[2022-03-05 10:30:53,757] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-04T10:29:52.784989+00:00 [queued]>
[2022-03-05 10:30:53,778] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-04T10:29:52.784989+00:00 [queued]>
[2022-03-05 10:30:53,780] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-05 10:30:53,782] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-05 10:30:53,783] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-05 10:30:53,820] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cat.cat_get_data> on 2022-03-04 10:29:52.784989+00:00
[2022-03-05 10:30:53,830] {standard_task_runner.py:52} INFO - Started process 529 to run task
[2022-03-05 10:30:53,841] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'cat.cat_get_data', 'scheduled__2022-03-04T10:29:52.784989+00:00', '--job-id', '549', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpep0sibfg', '--error-file', '/tmp/tmp_qpex_x2']
[2022-03-05 10:30:53,851] {standard_task_runner.py:77} INFO - Job 549: Subtask cat.cat_get_data
[2022-03-05 10:30:53,986] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-03-04T10:29:52.784989+00:00 [running]> on host ff48034dfdbf
[2022-03-05 10:30:54,111] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=cat.cat_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-04T10:29:52.784989+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-04T10:29:52.784989+00:00
[2022-03-05 10:31:54,071] {python.py:175} INFO - Done. Returned value was: None
[2022-03-05 10:31:54,106] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=cat.cat_get_data, execution_date=20220304T102952, start_date=20220305T103053, end_date=20220305T103154
[2022-03-05 10:31:54,132] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-05 10:31:54,171] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
