[2022-02-23 21:38:55,637] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [queued]>
[2022-02-23 21:38:55,663] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [queued]>
[2022-02-23 21:38:55,664] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:38:55,665] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 21:38:55,667] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:38:55,690] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cat.cat_get_data> on 2022-02-22 21:37:49.340300+00:00
[2022-02-23 21:38:55,704] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'cat.cat_get_data', 'scheduled__2022-02-22T21:37:49.340300+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpd9kuy5cd', '--error-file', '/tmp/tmp0x1s6hgk']
[2022-02-23 21:38:55,706] {standard_task_runner.py:77} INFO - Job 119: Subtask cat.cat_get_data
[2022-02-23 21:38:55,699] {standard_task_runner.py:52} INFO - Started process 141 to run task
[2022-02-23 21:38:55,819] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [running]> on host ff48034dfdbf
[2022-02-23 21:38:55,931] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=cat.cat_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-22T21:37:49.340300+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-22T21:37:49.340300+00:00
[2022-02-23 21:39:55,952] {python.py:175} INFO - Done. Returned value was: None
[2022-02-23 21:39:55,966] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=cat.cat_get_data, execution_date=20220222T213749, start_date=20220223T213855, end_date=20220223T213955
[2022-02-23 21:39:56,028] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 21:39:56,096] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
